import Head from "next/head";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import c from "../styles.module.css";
import Header from "../components/Header";
import CourseItem from "../components/CourseItem";

export default function Home({ courses }) {
  const [filteredCourses, setFilteredCourses] = useState(courses);
  const [location, setLocation] = useState("");
  const [category, setCategory] = useState("");
  const [deliveryMethods, setDeliveryMethods] = useState("");
  const [paginationOffset, setPaginationOffset] = useState(10);

  const searchParams = useSearchParams();
  const locationParam = searchParams.get("location") || "";
  const categoryParam = searchParams.get("category") || "";
  const deliveryMethodsParam = searchParams.get("deliveryMethods") || "";

  const disableSearch = !location && !category && !deliveryMethods;

  useEffect(() => {
    setLocation(locationParam);
    setCategory(categoryParam);
    setDeliveryMethods(deliveryMethodsParam);
  }, [locationParam, categoryParam, deliveryMethodsParam]);

  const allLocations = courses.map((course) => {
    return course.location;
  });
  const uniqueLocations = [...new Set(allLocations)];

  const allCategories = courses.map((course) => {
    return course.category;
  });
  const uniqueCategories = [...new Set(allCategories)];

  const alldeliveryMethods = courses.map((course) => {
    return course.deliveryMethod;
  });
  const uniqueDeliveryMethods = [...new Set(alldeliveryMethods)];

  const handleSearch = async () => {
    const search = { location, category, deliveryMethods };
    const searchParams = new URLSearchParams(search);
    const queryString = searchParams.toString();

    const response = await fetch(
      `http://localhost:8000/courses/search?${queryString}`
    );
    const data = await response.json();

    setFilteredCourses(data);
  };

  const saveSearch = async () => {
    const search = { location, category, deliveryMethods };

    fetch(`http://localhost:8000/courses/savedsearches`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ userSearchParams: search }),
    });
  };

  const saveCourse = async (courseId) => {
    fetch(`http://localhost:8000/courses/savedcourses`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ courseId }),
    });
  };

  const handleLoadMore = async () => {
    setPaginationOffset(paginationOffset + 10);
    const search = {
      location,
      category,
      deliveryMethods,
      offset: paginationOffset,
    };
    const searchParams = new URLSearchParams(search);
    const queryString = searchParams.toString();

    const response = await fetch(
      `http://localhost:8000/courses/search?${queryString}`
    );
    const data = await response.json();

    setFilteredCourses([...filteredCourses, ...data]);
  };

  return (
    <>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container">
        <div className={c.mainWrapper}>
          <h1>Courses</h1>
          <div className={c.selectWrapper}>
            <label htmlFor="location">
              Choose location:
              <select
                name="location"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                aria-label="Select location"
              >
                <option disabled value="">
                  Location
                </option>
                {uniqueLocations.map((location, index) => {
                  return <option key={index}>{location}</option>;
                })}
              </select>
            </label>
          </div>
          <div className={c.selectWrapper}>
            <label htmlFor="category">
              Choose category:
              <select
                name="category"
                aria-label="Select category"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
              >
                <option disabled value="">
                  Category
                </option>
                {uniqueCategories.map((category, index) => {
                  return <option key={index}>{category}</option>;
                })}
              </select>
            </label>
          </div>
          <div className={c.selectWrapper}>
            <label htmlFor="deliveryMethods">
              Choose deliveryMethods:
              <select
                name="deliveryMethods"
                aria-label="Select deliveryMethods"
                value={deliveryMethods}
                onChange={(e) => setDeliveryMethods(e.target.value)}
              >
                <option disabled value="">
                  DeliveryMethods
                </option>
                {uniqueDeliveryMethods.map((deliveryMethods, index) => {
                  return <option key={index}>{deliveryMethods}</option>;
                })}
              </select>
            </label>
          </div>
          <button onClick={handleSearch} disabled={disableSearch}>
            Search
          </button>
          <button onClick={saveSearch} disabled={disableSearch}>
            Save search
          </button>
          {filteredCourses.length > 0 ? (
            filteredCourses.map((course) => (
              <CourseItem
                course={course}
                saveCourse={() => saveCourse(course.courseId)}
                key={course.id}
              />
            ))
          ) : (
            <p>No courses found</p>
          )}
          <button onClick={handleLoadMore}>Load More</button>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://localhost:8000/courses");
  const courses = await res.json();
  return { props: { courses } };
}
